### Find Tickets - Tanpa Filter Class
GET http://localhost:8080/tickets/find?departure_station=GMR&arrival_station=SBY&departure_date=2026-01-05&count_passenger=2
Content-Type: application/json

###

### Find Tickets - Dengan Filter Class (Ekonomi)
GET http://localhost:8080/tickets/find?departure_station=GMR&arrival_station=SBY&departure_date=2026-01-05&count_passenger=1&filter_class=Ekonomi
Content-Type: application/json

###

### Find Tickets - Dengan Filter Class (Bisnis)
GET http://localhost:8080/tickets/find?departure_station=GMR&arrival_station=SBY&departure_date=2026-01-05&count_passenger=2&filter_class=Bisnis
Content-Type: application/json

###

### Find Tickets - Dengan Filter Class (Eksekutif)
GET http://localhost:8080/tickets/find?departure_station=GMR&arrival_station=SBY&departure_date=2026-01-05&count_passenger=3&filter_class=Eksekutif
Content-Type: application/json

